In [1]:
import numpy as np

In [2]:
# Basic Array Creation
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [6]:
arr = np.zeros((4,8)) # ((rows, columns))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
# “1 থেকে 5 এর মধ্যে 6টা number বানাও (equal gap দিয়ে)”
arr = np.linspace(1,5,6) # np.linspace(start, stop, num)   
arr #  gap = (stop - start) / (num - 1) 

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [9]:
np.random.rand(10) # normalization

array([0.68545831, 0.1532601 , 0.08751903, 0.17198669, 0.77035095,
       0.87583193, 0.43541964, 0.02468383, 0.70996849, 0.40805736])

In [10]:
np.random.randn(10) # standarization

array([ 1.11983776, -0.17255992,  0.78993632,  0.35392394,  0.44572404,
       -0.31376713,  1.35127041,  0.39731049,  0.64404193, -0.20153899])

In [11]:
np.random.randint(6) # generate any random number 0 - 6

4

In [12]:
np.random.randint(10, 20, 10) # np.random.randint(start, stop, number)

array([17, 18, 10, 15, 14, 11, 14, 11, 13, 16], dtype=int32)

In [13]:
# Array Attributes
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.shape # return the martix shape like row, column

(3, 3)

In [15]:
arr.size # return the array size / toal elements

9

In [16]:
arr.dtype

dtype('int64')

In [17]:
# Array Methods
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.max()

np.int64(9)

In [20]:
arr.sum()

np.int64(45)

In [21]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [22]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.mean() # mean = সব সংখ্যার যোগফল / মোট সংখ্যা = 45 / 9 = 5 = 5.0

np.float64(5.0)

In [25]:
arr.mean(axis=0) # column-wise mean

array([4., 5., 6.])

In [26]:
arr.mean(axis=1) # row-wise mean

array([2., 5., 8.])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.std()

np.float64(2.581988897471611)

In [29]:
"""
তোমার data: 1, 2, 3, 4, 5, 6, 7, 8, 9
mean (গড়) = 5
Step 1: প্রতিটা সংখ্যার থেকে mean বাদ দাও
1 - 5 = -4
2 - 5 = -3
3 - 5 = -2
4 - 5 = -1
5 - 5 =  0
6 - 5 =  1
7 - 5 =  2
8 - 5 =  3
9 - 5 =  4
Step 2: এগুলোর square (বর্গ) করো
(-4)^2 = 16
(-3)^2 = 9
(-2)^2 = 4
(-1)^2 = 1
 0^2   = 0
 1^2   = 1
 2^2   = 4
 3^2   = 9
 4^2   = 16
 Step 3: সবগুলো যোগ করো
 16 + 9 + 4 + 1 + 0 + 1 + 4 + 9 + 16 = 60
 Step 4: মোট সংখ্যা দিয়ে ভাগ (N = 9)
 60 / 9 = 6.666...
 Step 5: square root (√) নাও
 √6.666... ≈ 2.58
"""

'\nতোমার data: 1, 2, 3, 4, 5, 6, 7, 8, 9\nmean (গড়) = 5\nStep 1: প্রতিটা সংখ্যার থেকে mean বাদ দাও\n1 - 5 = -4\n2 - 5 = -3\n3 - 5 = -2\n4 - 5 = -1\n5 - 5 =  0\n6 - 5 =  1\n7 - 5 =  2\n8 - 5 =  3\n9 - 5 =  4\nStep 2: এগুলোর square (বর্গ) করো\n(-4)^2 = 16\n(-3)^2 = 9\n(-2)^2 = 4\n(-1)^2 = 1\n 0^2   = 0\n 1^2   = 1\n 2^2   = 4\n 3^2   = 9\n 4^2   = 16\n Step 3: সবগুলো যোগ করো\n 16 + 9 + 4 + 1 + 0 + 1 + 4 + 9 + 16 = 60\n Step 4: মোট সংখ্যা দিয়ে ভাগ (N = 9)\n 60 / 9 = 6.666...\n Step 5: square root (√) নাও\n √6.666... ≈ 2.58\n'

In [28]:
arr.argmax()

np.int64(8)

In [29]:
arr.argmax(axis=0)  # column-wise max value index

array([2, 2, 2])

In [30]:
arr.argmax(axis=1)  # row-wise

array([2, 2, 2])

In [31]:
arr.argmin()

np.int64(0)

In [32]:
arr.argmin(axis=0) # column-wise min value index

array([0, 0, 0])

In [33]:
arr.argmin(axis=1) # row-wise min value index

array([0, 0, 0])

In [ ]:
# Reshaping and resizing 

In [34]:
arr = np.arange(1,31) # create a vector 1 - 30 elements 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
arr = arr.reshape(6,5) # arr.reshape(row, col) = 6 * 5 = 30elements

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])