In [91]:
import numpy as np

In [92]:
#------------------Arithmetic Operations-------------------

In [93]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2

array([ 7,  9, 11, 13, 15])

In [94]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [95]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [96]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [97]:
a1 // a2

array([0, 0, 0, 0, 0])

In [98]:
a1 ** a2 # 1^6, 2^7, 3^8, 4^9, 5^10

array([      1,     128,    6561,  262144, 9765625])

In [99]:
# arr2 

In [100]:
#------------------Broadcasting-------------------

In [101]:
l = [10,20,30,40]
arr = np.array(l)

In [102]:
arr + 10

array([20, 30, 40, 50])

In [103]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [104]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [105]:
arr2 * 2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

In [106]:
#------------------Deep and Shallow copy-------------------

In [107]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [108]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [109]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [110]:
b = a.copy()

In [111]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [112]:
b[0] = 99 # b array index 0 = 99 it also change in a array but if we use a.copy then it not happend

In [113]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [114]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [115]:
#------------------Matrix operations-------------------

In [116]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [117]:
A

array([[1, 2],
       [3, 4]])

In [118]:
B

array([[5, 6],
       [7, 8]])

In [120]:
# Multiplication Matrix -> @
A @ B 

array([[19, 22],
       [43, 50]])

In [121]:
"""
| (1*5 + 2*7)  (1*6 + 2*8) |
| (3*5 + 4*7)  (3*6 + 4*8) |
"""

'\n| (1*5 + 2*7)  (1*6 + 2*8) |\n| (3*5 + 4*7)  (3*6 + 4*8) |\n'

In [122]:
# We can do the same matrix by using np.dot(A,B)
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [123]:
# Transpose mean row become columns 
A

array([[1, 2],
       [3, 4]])

In [124]:
# Transpose now A by A.T
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
#------------------Advance Array Manipulations-------------------

In [ ]:
# Stacking Array

In [125]:
# note: we can'not stack two matrix but we can stack two vectors below example:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [126]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [130]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#------------------Spliting Array-------------------

In [131]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
np.hsplit(c,2) # we can't split by 3 because the martix have 4 by 4 matrix but 4 is applicable

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [134]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [139]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [140]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [141]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
