In [1]:
import numpy as np

In [2]:
# -------------- Numpy Indexing and Slicing of Vectors-------------------
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr_slice = arr[3::2] # now it start from index 3 = 14 to 20 and 
arr_slice

array([14, 16, 18, 20])

In [4]:
# NUMPY INDEXING AND SLICING OF MATRIX
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr[0,0] # arr[row, col] = 1

np.int64(1)

In [6]:
# select 5 from the matrix
arr[0,4] 

np.int64(5)

In [7]:
# select 30 from the matrix
arr[5,4]

np.int64(30)

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
# now slice 2,7,3,8 from the matrix
arr[0:2,1:3] # arr[row_start:row_end , col_start:col_end]

array([[2, 3],
       [7, 8]])

In [17]:
# now slice 12, 17, 13, 18 from the matrix
slice = arr[2:4, 1:3]
slice

array([[12, 13],
       [17, 18]])

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
# now slice 19, 24, 29, 20, 25, 30 from the matrix
slice = arr[3: , 3: ]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [20]:
#---------------Boolean Indexing-------------------
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
# print all even values only from this vector
bool_index = arr % 2 == 0
bool_index

array([ True,  True,  True,  True,  True])

In [24]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])